--- # First Yaml playbook for Ansible
- hosts: apacheweb
  user: test
  become_user: sudo
  connection: ssh
  gather_facts: no
  vars:
     playbook_version: 0.1b
  vars_files:
     - ~/playbooks/conf/copyright.yml
     - ~/playbooks/conf/webdefaults.yml
  vars_prompt:
     - name: web_domain
       prompt: Web Domain
