- hosts: apacheweb
  vars: 
    control_server: linuxnoob4.mylabserver.com
    web_root: /var/www/html/
  tasks:
  - name: Install Lynx on App Server
    yum: pkg=lynx state=installed update_cache=true